# Generated by Django 3.1.1 on 2020-10-08 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0002_comprasdet_comprasenc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name_plural': 'Proveedores'},
        ),
    ]
